#    _____     _                      _       _____                
#   |  ___|   (_)                    | |     /  ___|                 
#   | |__ _ __ ___   ____ _ _ __   __| | ___ \ `--.  ___ _ __   __ _ 
#   |  __| '__| \ \ / / _` | '_ \ / _` |/ _ \ `--. \/ _ \ '_ \ / _` |
#   | |__| |  | |\ V / (_| | | | | (_| | (_) /\__/ /  __/ | | | (_| |
#   \____/_|  |_| \_/ \__,_|_| |_|\__,_|\___/\____/ \___|_| |_|\__,_|
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

lang: pt
title: Erivando Sena
description: >- 
  Pensamentos, 
  hist贸rias, 
  ideias 
  e c贸digos
# description: "Pensamentos, hist贸rias, ideias e c贸digos"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.erivandosena.com.br" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Erivando Sena
  twitter: erivandosena
  picture: /assets/images/johndoe.png
logo: /assets/icons/basically-basic-logo-dark.svg
# twitter_username: ""
github_username:  erivandosena
email: erivandosena@gmail.com
search: true
search_full_content: true
search_provider: algolia
algolia:
  application_id: SVWYKC6887
  index_name: basically-basic
  search_only_api_key: 73cbd4a7d10bcf3017e09da6f9bda8e2
  powered_by: false # true (default), false

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
      comments: false
      author: Erivando     # Default author for posts
  # _projects
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: post
      read_time: true

#  Asciidoctor is a fast text processor and publishing toolchain for converting
#  AsciiDoc content to HTML5, DocBook 5 (or 4.5) and other formats.
#
#  https://github.com/asciidoctor/jekyll-asciidoc
#  https://github.com/asciidoctor
#
#

asciidoctor-enabled: false
asciidoctor:
  description: 
  attributes:
    source-highlighter: coderay
    coderay-css: style
    icons: font